-- drops
DROP TABLE LOG_LOT CASCADE CONSTRAINTS;
DROP TABLE MANUTENCOES CASCADE CONSTRAINTS;
DROP TABLE DEFEITOS CASCADE CONSTRAINTS;
DROP TABLE VISITAS_TECNICAS CASCADE CONSTRAINTS;
DROP TABLE TECNICOS_EMPRESAS CASCADE CONSTRAINTS;
DROP TABLE EMPRESA_CONTATOS CASCADE CONSTRAINTS;
DROP TABLE TECNICOS CASCADE CONSTRAINTS;
DROP TABLE VEICULOS CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE EMPRESAS CASCADE CONSTRAINTS;
DROP TABLE CONTATOS CASCADE CONSTRAINTS;
DROP TABLE LOTS CASCADE CONSTRAINTS;
DROP TABLE CATALOGO_ACOES CASCADE CONSTRAINTS;
DROP TABLE CATALOGO_DEFEITOS CASCADE CONSTRAINTS;
DROP TABLE CATALOGO_EVENTOS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_USUARIOS;
DROP SEQUENCE SEQ_EMPRESAS;
DROP SEQUENCE SEQ_CONTATOS;
DROP SEQUENCE SEQ_VEICULOS;
DROP SEQUENCE SEQ_TECNICOS;
DROP SEQUENCE SEQ_VISITAS_TECNICAS;
DROP SEQUENCE SEQ_LOTS;
DROP SEQUENCE SEQ_CATALOGO_DEFEITOS;
DROP SEQUENCE SEQ_CATALOGO_ACOES;
DROP SEQUENCE SEQ_CATALOGO_EVENTOS;
DROP SEQUENCE SEQ_DEFEITOS;
DROP SEQUENCE SEQ_MANUTENCOES;
DROP SEQUENCE SEQ_LOG_LOT;


-- create tables principais
CREATE TABLE USUARIOS (
    id_usuario NUMBER NOT NULL,
    nome_completo VARCHAR2(200) NOT NULL,
    email_usuario VARCHAR2(200) NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (id_usuario),
    CONSTRAINT UK_USUARIOS_EMAIL UNIQUE (email_usuario)
);

CREATE TABLE EMPRESAS (
    id_empresa NUMBER NOT NULL,
    nome_fantasia VARCHAR2(200) NOT NULL,
    endereco VARCHAR2(200) NOT NULL,
    CONSTRAINT PK_EMPRESAS PRIMARY KEY (id_empresa)
);

CREATE TABLE CONTATOS (
    id_contato NUMBER NOT NULL,
    nome_contato VARCHAR2(200) NOT NULL,
    email_contato VARCHAR2(200),
    telefone VARCHAR2(20),
    CONSTRAINT PK_CONTATOS PRIMARY KEY (id_contato),
    CONSTRAINT CK_CONTATO_INFO CHECK (email_contato IS NOT NULL OR telefone IS NOT NULL)
);

CREATE TABLE TECNICOS (
    id_tecnico NUMBER NOT NULL,
    local VARCHAR2(200) NOT NULL,
    status VARCHAR2(8) DEFAULT 'ATIVO' NOT NULL,
    id_contato NUMBER NOT NULL,
    CONSTRAINT PK_TECNICOS PRIMARY KEY (id_tecnico),
    CONSTRAINT CK_TECNICOS_STATUS CHECK (status IN ('ATIVO', 'INATIVO')) -- Garante a integridade
);

CREATE TABLE VEICULOS (
    id_veiculo NUMBER NOT NULL,
    placa VARCHAR2(7) NOT NULL,
    frota VARCHAR2(15),
    id_empresa NUMBER NOT NULL,
    CONSTRAINT PK_VEICULOS PRIMARY KEY (id_veiculo),
    CONSTRAINT UK_VEICULOS_PLACA UNIQUE (placa)
);

CREATE TABLE LOTS (
    id_lot NUMBER NOT NULL,
    codigo_lot VARCHAR2(7) NOT NULL,
    obs_lot VARCHAR2(255),
    CONSTRAINT PK_LOTS PRIMARY KEY (id_lot),
    CONSTRAINT UK_LOTS_CODIGO UNIQUE (codigo_lot)
);

CREATE TABLE CATALOGO_DEFEITOS (
    id_catalogo_defeito NUMBER NOT NULL,
    codigo_defeito VARCHAR2(50) NOT NULL,
    descricao_defeito VARCHAR2(255),
    CONSTRAINT PK_CATALOGO_DEFEITOS PRIMARY KEY (id_catalogo_defeito)
);

CREATE TABLE CATALOGO_ACOES (
    id_catalogo_acao NUMBER NOT NULL,
    codigo_acao VARCHAR2(50) NOT NULL,
    descricao_acao VARCHAR2(255),
    CONSTRAINT PK_CATALOGO_ACOES PRIMARY KEY (id_catalogo_acao)
);

CREATE TABLE CATALOGO_EVENTOS (
    id_catalogo_eventos NUMBER NOT NULL,
    codigo_evento VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_CATALOGO_EVENTOS PRIMARY KEY (id_catalogo_eventos)
);

-- create juncao e eventos
CREATE TABLE EMPRESA_CONTATOS (
    id_empresa NUMBER NOT NULL,
    id_contato NUMBER NOT NULL,
    CONSTRAINT PK_EMPRESA_CONTATOS PRIMARY KEY (id_empresa, id_contato)
);

CREATE TABLE TECNICOS_EMPRESAS (
    id_tecnico NUMBER NOT NULL,
    id_empresa NUMBER NOT NULL,
    CONSTRAINT PK_TECNICOS_EMPRESAS PRIMARY KEY (id_tecnico, id_empresa)
);

CREATE TABLE VISITAS_TECNICAS (
    id_visita NUMBER NOT NULL,
    id_tecnico NUMBER NOT NULL,
    data_visita DATE NOT NULL,
    CONSTRAINT PK_VISITAS_TECNICAS PRIMARY KEY (id_visita)
);

CREATE TABLE DEFEITOS (
    id_defeito NUMBER NOT NULL,
    id_catalogo_defeito NUMBER NOT NULL,
    id_veiculo NUMBER NOT NULL,
    data_reporte DATE NOT NULL,
    status_defeito VARCHAR2(50) DEFAULT 'ATIVO' NOT NULL,
    obs_defeitos CLOB,
    CONSTRAINT PK_DEFEITOS PRIMARY KEY (id_defeito)
);

CREATE TABLE MANUTENCOES (
    id_manutencao NUMBER NOT NULL,
    id_visita NUMBER NOT NULL,
    id_catalogo_acao NUMBER NOT NULL,
    id_defeito NUMBER NOT NULL,
    obs_servico CLOB,
    CONSTRAINT PK_MANUTENCOES PRIMARY KEY (id_manutencao)
);

CREATE TABLE LOG_LOT (
    id_log NUMBER NOT NULL,
    id_lot NUMBER NOT NULL,
    id_veiculo NUMBER,
    id_empresa NUMBER,
    id_manutencao NUMBER,
    id_catalogo_eventos NUMBER NOT NULL,
    data_evento DATE NOT NULL,
    responsavel_evento VARCHAR2(100) NOT NULL,
    obs_evento CLOB,
    CONSTRAINT PK_LOG_LOT PRIMARY KEY (id_log)
);


-- sequences
CREATE SEQUENCE SEQ_USUARIOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EMPRESAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTATOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VEICULOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TECNICOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VISITAS_TECNICAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATALOGO_DEFEITOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATALOGO_ACOES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATALOGO_EVENTOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEFEITOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MANUTENCOES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOG_LOT START WITH 1 INCREMENT BY 1;


-- fk (RELACIONAMENTOS)
ALTER TABLE VEICULOS ADD CONSTRAINT FK_VEICULOS_EMPRESAS FOREIGN KEY (id_empresa) REFERENCES EMPRESAS (id_empresa);
ALTER TABLE EMPRESA_CONTATOS ADD CONSTRAINT FK_EMPRESACONTATOS_EMPRESAS FOREIGN KEY (id_empresa) REFERENCES EMPRESAS (id_empresa);
ALTER TABLE EMPRESA_CONTATOS ADD CONSTRAINT FK_EMPRESACONTATOS_CONTATOS FOREIGN KEY (id_contato) REFERENCES CONTATOS (id_contato);
ALTER TABLE TECNICOS ADD CONSTRAINT FK_TECNICOS_CONTATOS FOREIGN KEY (id_contato) REFERENCES CONTATOS (id_contato);
ALTER TABLE TECNICOS_EMPRESAS ADD CONSTRAINT FK_TECEMPRESAS_TECNICOS FOREIGN KEY (id_tecnico) REFERENCES TECNICOS (id_tecnico);
ALTER TABLE TECNICOS_EMPRESAS ADD CONSTRAINT FK_TECEMPRESAS_EMPRESAS FOREIGN KEY (id_empresa) REFERENCES EMPRESAS (id_empresa);
ALTER TABLE VISITAS_TECNICAS ADD CONSTRAINT FK_VISITAS_TECNICOS FOREIGN KEY (id_tecnico) REFERENCES TECNICOS (id_tecnico);
ALTER TABLE DEFEITOS ADD CONSTRAINT FK_DEFEITOS_CATALOGO FOREIGN KEY (id_catalogo_defeito) REFERENCES CATALOGO_DEFEITOS (id_catalogo_defeito);
ALTER TABLE DEFEITOS ADD CONSTRAINT FK_DEFEITOS_VEICULOS FOREIGN KEY (id_veiculo) REFERENCES VEICULOS (id_veiculo);
ALTER TABLE MANUTENCOES ADD CONSTRAINT FK_MANUTENCOES_VISITAS FOREIGN KEY (id_visita) REFERENCES VISITAS_TECNICAS (id_visita);
ALTER TABLE MANUTENCOES ADD CONSTRAINT FK_MANUTENCOES_CATALOGOACOES FOREIGN KEY (id_catalogo_acao) REFERENCES CATALOGO_ACOES (id_catalogo_acao);
ALTER TABLE MANUTENCOES ADD CONSTRAINT FK_MANUTENCOES_DEFEITOS FOREIGN KEY (id_defeito) REFERENCES DEFEITOS (id_defeito);
ALTER TABLE LOG_LOT ADD CONSTRAINT FK_LOG_LOTS FOREIGN KEY (id_lot) REFERENCES LOTS (id_lot);
ALTER TABLE LOG_LOT ADD CONSTRAINT FK_LOG_VEICULOS FOREIGN KEY (id_veiculo) REFERENCES VEICULOS (id_veiculo);
ALTER TABLE LOG_LOT ADD CONSTRAINT FK_LOG_EMPRESAS FOREIGN KEY (id_empresa) REFERENCES EMPRESAS (id_empresa);
ALTER TABLE LOG_LOT ADD CONSTRAINT FK_LOG_MANUTENCOES FOREIGN KEY (id_manutencao) REFERENCES MANUTENCOES (id_manutencao);
ALTER TABLE LOG_LOT ADD CONSTRAINT FK_LOG_CATALOGOEVENTOS FOREIGN KEY (id_catalogo_eventos) REFERENCES CATALOGO_EVENTOS (id_catalogo_eventos);

-- garantir acesso