-- ========= DROPS (TABELAS E SEQUENCES) =========
DROP TABLE MANUTENCOES CASCADE CONSTRAINTS;
DROP TABLE EMPRESA_CONTATOS CASCADE CONSTRAINTS;
DROP TABLE DEFEITOS CASCADE CONSTRAINTS;
DROP TABLE VISITAS_TECNICAS CASCADE CONSTRAINTS;
DROP TABLE VEICULOS CASCADE CONSTRAINTS;
DROP TABLE TECNICOS CASCADE CONSTRAINTS;
DROP TABLE EMPRESAS CASCADE CONSTRAINTS;
DROP TABLE CONTATOS CASCADE CONSTRAINTS;
DROP TABLE CATALOGO_ACOES CASCADE CONSTRAINTS;
DROP TABLE CATALOGO_DEFEITOS CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CATALOGO_ACOES;
DROP SEQUENCE SEQ_CATALOGO_DEFEITOS;
DROP SEQUENCE SEQ_TECNICOS;
DROP SEQUENCE SEQ_VISITAS_TECNICAS;
DROP SEQUENCE SEQ_DEFEITOS;
DROP SEQUENCE SEQ_MANUTENCOES;


-- ========= TABELAS DE CATÁLOGO =========
CREATE TABLE CATALOGO_ACOES (
    id_catalogo_acao NUMBER NOT NULL,
    codigo_acao VARCHAR2(100) NOT NULL,
    descricao_acao VARCHAR2(255),
    CONSTRAINT PK_CATALOGO_ACAO PRIMARY KEY (id_catalogo_acao)
);

CREATE TABLE CATALOGO_DEFEITOS (
    id_catalogo_defeito NUMBER NOT NULL,
    codigo_defeito VARCHAR2(10) NOT NULL,
    descricao_defeito VARCHAR2(255),
    CONSTRAINT PK_CATALOGO_DEFEITO PRIMARY KEY (id_catalogo_defeito)
);


-- ========= TABELAS PRINCIPAIS =========
CREATE TABLE CONTATOS (
    id_contato VARCHAR2(100) NOT NULL,
    nome_contato VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_CONTATO PRIMARY KEY (id_contato)
);

CREATE TABLE TECNICOS (
    id_tecnico NUMBER NOT NULL,
    nome_tecnico VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_TECNICO PRIMARY KEY (id_tecnico)
);

CREATE TABLE EMPRESAS (
    id_empresa VARCHAR2(100) NOT NULL,
    nome_fantasia VARCHAR2(100) NOT NULL,
    endereco VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_EMPRESA PRIMARY KEY (id_empresa)
);


-- ========= TABELAS DEPENDENTES =========
CREATE TABLE VEICULOS (
    id_veiculo VARCHAR2(10) NOT NULL,
    id_empresa VARCHAR2(100) NOT NULL,
    placa VARCHAR2(8) NOT NULL,
    CONSTRAINT PK_VEICULO PRIMARY KEY (id_veiculo)
);

CREATE TABLE VISITAS_TECNICAS (
    id_visita NUMBER NOT NULL,
    id_tecnico NUMBER NOT NULL,
    data_visita DATE NOT NULL,
    CONSTRAINT PK_VISITA PRIMARY KEY (id_visita)
);

CREATE TABLE DEFEITOS (
    id_defeito NUMBER NOT NULL,
    data_reporte DATE NOT NULL,
    status_defeito VARCHAR2(20) NOT NULL,
    observacoes CLOB,
    id_catalogo_defeito NUMBER NOT NULL,
    id_veiculo VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_DEFEITO PRIMARY KEY (id_defeito)
);


-- ========= TABELAS DE JUNÇÃO E EVENTOS FINAIS =========
CREATE TABLE EMPRESA_CONTATOS (
    id_empresa VARCHAR2(100) NOT NULL,
    id_contato VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_EMPRESA_CONTATOS PRIMARY KEY (id_empresa, id_contato)
);

CREATE TABLE MANUTENCOES (
    id_manutencao NUMBER NOT NULL,
    observacoes_servico CLOB,
    id_visita NUMBER NOT NULL,
    id_defeito NUMBER NOT NULL,
    id_catalogo_acao NUMBER NOT NULL,
    CONSTRAINT PK_MANUTENCAO PRIMARY KEY (id_manutencao)
);


-- ========= SEQUENCES PARA GERAR IDs AUTOMÁTICOS =========
CREATE SEQUENCE SEQ_CATALOGO_ACOES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATALOGO_DEFEITOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TECNICOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VISITAS_TECNICAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEFEITOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MANUTENCOES START WITH 1 INCREMENT BY 1;


-- ========= CHAVES ESTRANGEIRAS (RELACIONAMENTOS) =========
ALTER TABLE VEICULOS ADD CONSTRAINT FK_VEICULOS_EMPRESAS
FOREIGN KEY (id_empresa) REFERENCES EMPRESAS (id_empresa);

ALTER TABLE EMPRESA_CONTATOS ADD CONSTRAINT FK_EMPRESACONTATOS_EMPRESAS
FOREIGN KEY (id_empresa) REFERENCES EMPRESAS (id_empresa);

ALTER TABLE EMPRESA_CONTATOS ADD CONSTRAINT FK_EMPRESACONTATOS_CONTATOS
FOREIGN KEY (id_contato) REFERENCES CONTATOS (id_contato);

ALTER TABLE VISITAS_TECNICAS ADD CONSTRAINT FK_VISITAS_TECNICOS
FOREIGN KEY (id_tecnico) REFERENCES TECNICOS (id_tecnico);

ALTER TABLE DEFEITOS ADD CONSTRAINT FK_DEFEITOS_VEICULOS
FOREIGN KEY (id_veiculo) REFERENCES VEICULOS (id_veiculo);

ALTER TABLE DEFEITOS ADD CONSTRAINT FK_DEFEITOS_CATALOGODEFEITOS
FOREIGN KEY (id_catalogo_defeito) REFERENCES CATALOGO_DEFEITOS (id_catalogo_defeito);

ALTER TABLE MANUTENCOES ADD CONSTRAINT FK_MANUTENCOES_VISITAS
FOREIGN KEY (id_visita) REFERENCES VISITAS_TECNICAS (id_visita);

ALTER TABLE MANUTENCOES ADD CONSTRAINT FK_MANUTENCOES_DEFEITOS
FOREIGN KEY (id_defeito) REFERENCES DEFEITOS (id_defeito);

ALTER TABLE MANUTENCOES ADD CONSTRAINT FK_MANUTENCOES_CATALOGOACOES
FOREIGN KEY (id_catalogo_acao) REFERENCES CATALOGO_ACOES (id_catalogo_acao);